"""changing pk's

Revision ID: 07b0a505dcef
Revises: 5333f840f7b7
Create Date: 2022-08-19 11:11:46.626154

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '07b0a505dcef'
down_revision = '5333f840f7b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
