"""migration2

Revision ID: 47ba2eb840b3
Revises: 42a02c91d760
Create Date: 2022-08-19 21:51:38.616989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47ba2eb840b3'
down_revision = '42a02c91d760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='tag')
    op.drop_table('tag')
    op.drop_table('card')
    op.drop_table('card_has_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_has_tag',
    sa.Column('card_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('card_id', 'tag_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('card',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('texto', mysql.TEXT(), nullable=False),
    sa.Column('data_criacao', mysql.DATETIME(), nullable=False),
    sa.Column('data_modificacao', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tag',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'tag', ['name'], unique=False)
    # ### end Alembic commands ###
