"""adding default field

Revision ID: 85cfd11fb9b8
Revises: df8d660ee5b9
Create Date: 2022-08-19 11:27:41.078801

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '85cfd11fb9b8'
down_revision = 'df8d660ee5b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
