"""adding card_has_tag relationship

Revision ID: bcb912a45f8f
Revises: 85cfd11fb9b8
Create Date: 2022-08-19 11:40:59.865545

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bcb912a45f8f'
down_revision = '85cfd11fb9b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
