"""changing card fields to allow null values

Revision ID: df8d660ee5b9
Revises: 07b0a505dcef
Create Date: 2022-08-19 11:18:07.596799

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df8d660ee5b9'
down_revision = '07b0a505dcef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'data_criacao',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'data_criacao',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
